### ISSUE TITLE
Inclusion of both `trailblazer-rails` and `neo4j` gems raises superclass mismatch error

### ISSUE THREAD

**Issue by thefliik** [trailblazer/trailblazer-rails#46]
While starting a new project and using both `trailblazer-rails` and the [`neo4j` gems](https://github.com/neo4jrb/neo4j/issues/1387), I encountered a `superclass missmatch error` when running `rake neo4j:migrate`. Commenting out the `trailblazer-rails gem` and then running `rake neo4j:migrate` allows the migration to run normally. Not sure what's going on beyond that.

Here's the backtrace:

```
Invoke neo4j:migrate (first_time)
** Execute neo4j:migrate
** Invoke neo4j:migrate:all (first_time)
** Invoke neo4j:allow_migrations (first_time)
** Execute neo4j:allow_migrations
** Invoke environment (first_time)
** Execute environment
** Execute neo4j:migrate:all
== 20170531220914 Person: running... ===========================================
rake aborted!
TypeError: superclass mismatch for class Person
/home/ubuntu/nonprofit-center-server/db/neo4j/migrate/20170531220914_person.rb:1:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/migration_file.rb:12:in `create'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:114:in `block in migrate'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:121:in `migration_message'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:113:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:26:in `block in all'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:24:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/migrations/runner.rb:24:in `all'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/tasks/migration.rake:53:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/neo4j-8.0.17/lib/neo4j/tasks/migration.rake:46:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/rake:22:in `load'
/home/ubuntu/.rvm/rubies/ruby-2.4.0/bin/rake:22:in `<main>'
Tasks: TOP => neo4j:migrate:all

```

**Comment by apotonick** [comment]
In `app/concepts/person`, you have files with the mismatching class definitions. Please follow http://trailblazer.to/guides/trailblazer/2.0/03-rails-basics.html#create (see the inline `BlogPost::Create`).

This is not related to neojs or TRB, but to Rails' loading order madness.

**Comment by thefliik** [comment]
Hi @apotonick, thanks for the super fast reply!! But I don't think what you've referenced is the issue. I just created a brand new project, [which you can see here](https://gitlab.com/john.carroll.p/issue-example-app), using `rails new test_app -m http://neo4jrb.io/neo4j/neo4j.rb --skip-yarn -M -O -C -S --skip-coffee -J --skip-turbolinks --api -B`. 

I then added the `trailblazer` and `trailblazer-rails` gems, ran `rake neo4j:install` + `rails g model Person` + `rake neo4j:start` + `rake neo4j:migrate`.

`rake neo4j:migrate` then generates a `superclase mismatch error`. There are no `app/concepts/*` directories (or anything relating to `trailblazer` other than what was included by `bundle install`).

**Comment by apotonick** [comment]
Then, the neo gem is doing something wrong and declaring the `Person` class without the appropriate superclass. 

TRB-rails simply loads `app/models` and the `app/concepts` directories at startup in a **well-defined order**, which in your case might differ from what neo is expecting. Can you check all occurences of the class `Person` and paste them here, please?

Yeah, I'm always very responsive in the early morning, so hurry up because it's getting close to lunch time :joy: ...

**Comment by thefliik** [comment]
In `db/neo4j/migrate/xxxxx_person.rb`
```
class Person < Neo4j::Migrations::Base
  def up
    add_constraint :Person, :uuid
  end

  def down
    drop_constraint :Person, :uuid
  end
end
```

In `app/models/person.rb`
```
class Person 
  include Neo4j::ActiveNode



end
```

All references to `Person` were created by `rails g model Person`. The output was:

```
      invoke  neo4j
      create    app/models/person.rb
      create    db/neo4j/migrate/20170602055411_person.rb
      invoke    test_unit
      create      test/models/person_test.rb
      create      test/fixtures/people.yml
```

Thanks! I also opened up [an issue on the `neo4j` gem.](https://github.com/neo4jrb/neo4j/issues/1387)

**Comment by apotonick** [comment]
Yepp, that's a bug in the `neo4j` gem, then. Two same-named classes with different superclasses don't work. The reason this breaks here is because TRB-rails loads the model before the migration.

**Comment by thefliik** [comment]
@apotonick, thanks so much for helping to diagnose the issue I was experiencing!!!!!
@cheerfulstoic went about fixing it super fast!
