### ISSUE TITLE
Circular dependency detected while autoloading constant ActiveStorage::Blob::Identifiable

### ISSUE THREAD

**Issue by mensfeld** [trailblazer/trailblazer-rails#66]
After bumping from 1.0.5 to 1.0.7:

```
Traceback (most recent call last):
  83: from bin/rails:4:in `<main>'
  82: from bin/rails:4:in `require'
  81: from gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
  80: from gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
  79: from gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
  78: from gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  77: from gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  76: from gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  75: from gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:95:in `perform'
  74: from gems/railties-5.2.0/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
  73: from gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
  72: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
  71: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
  70: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
  69: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
  68: from /home/mencio/Software/Coditsu/TMP/Kabe/config/environment.rb:7:in `<top (required)>'
  67: from gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
  66: from gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
  65: from 2.5.0/tsort.rb:205:in `tsort_each'
  64: from 2.5.0/tsort.rb:226:in `tsort_each'
  63: from 2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  62: from 2.5.0/tsort.rb:347:in `call'
  61: from 2.5.0/tsort.rb:347:in `each'
  60: from 2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  59: from 2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  58: from 2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  57: from 2.5.0/tsort.rb:228:in `block in tsort_each'
  56: from gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
  55: from gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
  54: from gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
  53: from gems/railties-5.2.0/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
  52: from gems/activesupport-5.2.0/lib/active_support/reloader.rb:89:in `prepare!'
  51: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
  50: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
  49: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
  48: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
  47: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
  46: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
  45: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
  44: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
  43: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
  42: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
  41: from gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `instance_exec'
  40: from gems/trailblazer-rails-1.0.7/lib/trailblazer/rails/railtie.rb:40:in `block (2 levels) in <class:Railtie>'
  39: from gems/trailblazer-rails-1.0.7/lib/trailblazer/rails/railtie.rb:15:in `load_concepts'
  38: from gems/trailblazer-rails-1.0.7/lib/trailblazer/rails/railtie.rb:15:in `each'
  37: from gems/trailblazer-rails-1.0.7/lib/trailblazer/rails/railtie.rb:15:in `block in load_concepts'
  36: from gems/trailblazer-rails-1.0.7/lib/trailblazer/rails/railtie.rb:27:in `load_for'
  35: from gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:33:in `call'
  34: from gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `load_files'
  33: from gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `each'
  32: from gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `block in load_files'
  31: from gems/trailblazer-rails-1.0.7/lib/trailblazer/rails/railtie.rb:27:in `block in load_for'
  30: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:242:in `require_dependency'
  29: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:326:in `depend_on'
  28: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:348:in `require_or_load'
  27: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `load_interlock'
  26: from gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:13:in `loading'
  25: from gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  24: from gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  23: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  22: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:365:in `block in require_or_load'
  21: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:467:in `load_file'
  20: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:653:in `new_constants_in'
  19: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `block in load_file'
  18: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `load'
  17: from gems/activestorage-5.2.0/app/models/active_storage/blob/identifiable.rb:3:in `<top (required)>'
  16: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
  15: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:502:in `load_missing_constant'
  14: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:348:in `require_or_load'
  13: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `load_interlock'
  12: from gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:13:in `loading'
  11: from gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  10: from gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
   9: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
   8: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:365:in `block in require_or_load'
   7: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:467:in `load_file'
   6: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:653:in `new_constants_in'
   5: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `block in load_file'
   4: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `load'
   3: from gems/activestorage-5.2.0/app/models/active_storage/blob.rb:16:in `<top (required)>'
   2: from gems/activestorage-5.2.0/app/models/active_storage/blob.rb:22:in `<class:Blob>'
   1: from gems/activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
gems/activesupport-5.2.0/lib/active_support/dependencies.rb:500:in `load_missing_constant': Circular dependency detected while autoloading constant ActiveStorage::Blob::Identifiable (RuntimeError)

```

**Comment by emaglio** [comment]
@mensfeld mhmhm weird...the only changes between the 2 versions is adding a config flag to disable the loader but default is true so if `config.trailblazer.use_loader = true` everything should work fine.
Which rails version are you using?

**Comment by mensfeld** [comment]
5.2.0 - this is the new one.

**Comment by emaglio** [comment]
@mensfeld can you please try this branch: https://github.com/emaglio/trailblazer-rails/tree/fix_rails_5_2

**Comment by mensfeld** [comment]
Works!

**Comment by emaglio** [comment]
@mensfeld cool, please use that branch because I want to wait @seuros or @apotonick to approve my PR before merging and releasing a new version

**Comment by mensfeld** [comment]
@emaglio ok. Will. When it is fixed, please don't forget to close this. I will get a notification and will be able to move back to the rubygems version.

**Comment by mensfeld** [comment]
@emaglio thank you. Works awesome!
